### ISSUE TITLE
Plugins not opening in Ubuntu 22.04

### ISSUE THREAD

**Issue by sisyphusmc** [sleiner/pizmidi#18]
I was able to compile the plugins in Ubuntu 22.04, as well as in Ubuntu 20.04 on a virtual machine. The resulting binaries from both compilations would not open for me in REAPER v. 6.68 or Carla in Ubuntu 22.04.

**Comment by sleiner** [comment]
Thanks for reporting! I have reproduced the bug with Reaper and will check for possible fixes...

**Comment by sleiner** [comment]
@sisyphusmc could you please test [these builds](https://github.com/sleiner/pizmidi/actions/runs/3185734351) from #20? On my system (Ubuntu 22.04, Reaper 6.68), they are working.

**Comment by sisyphusmc** [comment]
@sleiner Thanks so much for looking into it! Unfortunately still no luck, the plugins still fail to scan in Reaper and in Carla. In Reaper they appear in the "plugins that failed to scan" list on the the "Re-Scan" dropdown under the Vst Plugins settings. In Carla I rescan for new plugins and they just don't show up. 

I just compiled on Ubuntu 22.04 (used the cmake --build --preset=linux-native --parallel --target package to make a .zip file).  I get a bunch of warnings like these when compiling:

[505/541] Building CXX object pizjuce/midiStep/CMakeFiles/piz_midiStep.dir/Release/step.cpp.o
/pizmidi/pizjuce/midiStep/step.cpp: In member function ‘virtual const juce::String MidiStep::getInputChannelName(int) const’:
/pizmidi/pizjuce/midiStep/step.cpp:196:43: warning: ‘int juce::AudioProcessor::getNumInputChannels() const’ is deprecated [-Wdeprecated-declarations]
  196 |     if (channelIndex < getNumInputChannels())
      |                        ~~~~~~~~~~~~~~~~~~~^~
In file included from /pizmidi/build/linux-native/_deps/juce-src/modules/juce_audio_processors/juce_audio_processors.h:144,
                 from /pizmidi/pizjuce/midiStep/../_common/PizAudioProcessor.h:10,
                 from /pizmidi/pizjuce/midiStep/step.h:4,
                 from /pizmidi/pizjuce/midiStep/step.cpp:1:
/pizmidi/build/linux-native/_deps/juce-src/modules/juce_audio_processors/processors/juce_AudioProcessor.h:1428:24: note: declared here
 1428 |     [[deprecated]] int getNumInputChannels() const noexcept                   { return getTotalNumInputChannels(); }
      |                        ^~~~~~~~~~~~~~~~~~~

Is there some sort of log file I can send you which might be useful? Thanks for your patience and please forgive me if it's a dumb question, I have very little experience when it comes to compiling software from source and I'm not a programmer.

**Comment by sleiner** [comment]
No worries! :-)

Let's approach this step by step - here is what I do on my Ubuntu machine:

1. Download the [packages-ubuntu-20.04](https://github.com/sleiner/pizmidi/suites/8615624138/artifacts/386603763) artifact from the [builds page](https://github.com/sleiner/pizmidi/actions/runs/3185734351). For this test, I am **not using locally compiled plugins**.
2. Extract the ZIP archive to some folder (e.g. `/home/nameofmyuser/Downloads/pizmidi`)
3. Start Reaper and have an empty project
4. Open the `Plugins` -> `VST` page of the settings.
5. Ensure that _only_ the path where I extracted the archive to is set as VST plugin path
6. Click `Rescan` -> `Clear cache and re-scan VST paths for all plugins`
7. Close preferences
8. Insert a plugin (e.g. _midiPads_) on the master track.

What are your results if you follow these instructions?

<img width="807" alt="image" src="https://user-images.githubusercontent.com/6379313/194130015-a2be567b-111b-4d35-b9d2-110dd84fa055.png">

---

> I get a bunch of warnings like these when compiling

That is expected. The plugins contain a lot of legacy code which now (rightfully) triggers compiler warnings.

**Comment by sisyphusmc** [comment]
I followed the instructions and everything works! I hadn't realized that I could just download the binaries! Thanks again for all your help and for rebooting these awesome plugins. For me, midiLooper is a game changer as it gives reaper ableton-like looping capabilities. And as an added bonus from what I can see midiLooper's parameters are fully controlable by Helgoboss' Realearn so it should be possible to use an akai apc key 25 and have visual feedback as well!
